# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8853ee1c15d3863da22889b81028b01536eb7292d0bd1ddbbdb51da03325f20368d3e0475d296b2112e9077ae3ef27b9a7b609d1439a12e6ec363fcc0b45a0e6

test:
  secret_key_base: 921f9ab58237d4986b6140d25395e8c0e488647fc68aa6ab0d555783d281f5f030b4b4517c31d5605611fb047c4132a47482afff82a499919d12ee1379b3cf30

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
