# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b1bf19fc790838a9808c516c8c5ec9012f2ba3eb1b01f07bd1343f469aea5cfdad6573035a1a73468806b4666e9d4c312c6c0ad0a58de71e14ad79e04a30494

test:
  secret_key_base: 8cbb461d608c5f80395c37dc6d111339c7ffd1c486f5c4371a9af606468f51946c6b4c503bc9e070b419585b3f24880683158217fa9ba1b1f5fa7444d3807dcf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
