# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4906eeeca7ca18eff3a011ebecfa47d17b86e7d535bebc08bd7be1a6dd5741ccd4634306f95916f51e67ba3ffebbd8bca43875c86cd6e7a20be70b78350ac7be

test:
  secret_key_base: 7e8ef788e372ede93e3dbbfc8b263f1227e7f57cecab34aba935470314ae1e34b847192ad952149076a35afc0a28e06233226fcacf5263505cd326eb2a454c44

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
