# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 760d943656dd2bd59a3af504cac12c30b328d6172655c4a5bd40ec8aa3ce5bd3723f49078a084a0fb696c3debaa8e0ea564e17f016c1fb44e1c8a20150520821

test:
  secret_key_base: 1f4bf02c0c9e6c6c168f732c80b95e7a220269f01fbbd09198cca48cb51203baf5014797ebaf40e0bef8eb41b5fdc4b7f8c4e78b889d57094db065b3e38b7c85

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
