# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9bac7abaf09c40d711d3234834c3fc70df75ae0b1acc91dd1961a92aae4ba309572c840e61b2f4817751da04f5ec551e3b4efd482fb451ecb7fb9f4c1364245f

test:
  secret_key_base: 5c2923d02afd18f99350fd620561442b2b51feb78d82fd99a530b782de4723f2da101c5f6d7f4a087d6b9f442d4340c58e4360326aac5cb81e633174acfe1b06

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
